#############################################################################
# Makefile for building: copy3
# Generated by qmake (2.01a) (Qt 4.8.5) on: Mon Jan 18 16:58:07 2016
# Project:  copy3.pro
# Template: app
# Command: /usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/qmake -o Makefile copy3.pro
#############################################################################

####### Compiler, tools and options

CC            = arm-linux-gcc -lts
CXX           = arm-linux-g++ -lts
DEFINES       = -DQT_NO_DEBUG -DQT_SQL_LIB -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/qws/linux-arm-fsl-gnueabi-g++ -I. -I/usr/local/Trolltech/QtEmbedded-4.8.5-arm/include/QtCore -I/usr/local/Trolltech/QtEmbedded-4.8.5-arm/include/QtNetwork -I/usr/local/Trolltech/QtEmbedded-4.8.5-arm/include/QtGui -I/usr/local/Trolltech/QtEmbedded-4.8.5-arm/include/QtXml -I/usr/local/Trolltech/QtEmbedded-4.8.5-arm/include/QtSql -I/usr/local/Trolltech/QtEmbedded-4.8.5-arm/include -I. -I. -I.
LINK          = arm-linux-g++ -lts
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/local/Trolltech/QtEmbedded-4.8.5-arm/lib
LIBS          = $(SUBLIBS)  -L/usr/local/Trolltech/QtEmbedded-4.8.5-arm/lib -lQtSql -L/home/tangbin/tslib-install/lib -L/usr/local/Trolltech/QtEmbedded-4.8.5-arm/lib -lQtXml -lQtGui -lQtNetwork -lQtCore -lpthread -lts 
AR            = arm-linux-ar cqs
RANLIB        = 
QMAKE         = /usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = arm-linux-strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		newconfiginfo.cpp \
		changeof351andrfid.cpp \
		TestInput_Cursor/formhanzitable.cpp \
		TestInput_Cursor/formsymbolpad.cpp \
		TestInput_Cursor/HanziManager.cpp \
		TestInput_Cursor/formhanziselector.cpp \
		TestInput_Cursor/formnumpad.cpp \
		TestInput_Cursor/padbase.cpp \
		TestInput_Cursor/keyboard.cpp \
		TestInput_Cursor/dialogtooltip.cpp \
		TestInput_Cursor/inputmethod.cpp \
		optiondialog.cpp \
		save.cpp \
		basicset.cpp \
		fisupdate.cpp \
		communication.cpp \
		tightenthread.cpp \
		xmlcreate.cpp \
		inputevents.cpp \
		wificonnect.cpp \
		reinsertserverdb.cpp \
		taotong.cpp \
		sqlthread.cpp \
		split.cpp \
		serialcom.cpp moc_mainwindow.cpp \
		moc_newconfiginfo.cpp \
		moc_changeof351andrfid.cpp \
		moc_formhanzitable.cpp \
		moc_keyboard.cpp \
		moc_dialogtooltip.cpp \
		moc_formhanziselector.cpp \
		moc_formnumpad.cpp \
		moc_formsymbolpad.cpp \
		moc_inputmethod.cpp \
		moc_padbase.cpp \
		moc_optiondialog.cpp \
		moc_save.cpp \
		moc_basicset.cpp \
		moc_fisupdate.cpp \
		moc_communication.cpp \
		moc_tightenthread.cpp \
		moc_xmlcreate.cpp \
		moc_inputevents.cpp \
		moc_wificonnect.cpp \
		moc_reinsertserverdb.cpp \
		moc_taotong.cpp \
		moc_sqlthread.cpp \
		moc_split.cpp \
		qrc_file.cpp \
		qrc_keypad.cpp
OBJECTS       = main.o \
		mainwindow.o \
		newconfiginfo.o \
		changeof351andrfid.o \
		formhanzitable.o \
		formsymbolpad.o \
		HanziManager.o \
		formhanziselector.o \
		formnumpad.o \
		padbase.o \
		keyboard.o \
		dialogtooltip.o \
		inputmethod.o \
		optiondialog.o \
		save.o \
		basicset.o \
		fisupdate.o \
		communication.o \
		tightenthread.o \
		xmlcreate.o \
		inputevents.o \
		wificonnect.o \
		reinsertserverdb.o \
		taotong.o \
		sqlthread.o \
		split.o \
		serialcom.o \
		moc_mainwindow.o \
		moc_newconfiginfo.o \
		moc_changeof351andrfid.o \
		moc_formhanzitable.o \
		moc_keyboard.o \
		moc_dialogtooltip.o \
		moc_formhanziselector.o \
		moc_formnumpad.o \
		moc_formsymbolpad.o \
		moc_inputmethod.o \
		moc_padbase.o \
		moc_optiondialog.o \
		moc_save.o \
		moc_basicset.o \
		moc_fisupdate.o \
		moc_communication.o \
		moc_tightenthread.o \
		moc_xmlcreate.o \
		moc_inputevents.o \
		moc_wificonnect.o \
		moc_reinsertserverdb.o \
		moc_taotong.o \
		moc_sqlthread.o \
		moc_split.o \
		qrc_file.o \
		qrc_keypad.o
DIST          = /usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/common/unix.conf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/common/linux.conf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/common/qws.conf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/qconfig.pri \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/release.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/shared.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/qt.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/moc.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/resources.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/uic.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/lex.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/include_source_dir.prf \
		copy3.pro
QMAKE_TARGET  = copy3
DESTDIR       = 
TARGET        = copy3

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_newconfiginfo.h ui_formsymbolpad.h ui_formnumpad.h ui_formhanziselector.h ui_keyboard.h ui_dialogtooltip.h ui_formhanzitable.h ui_optiondialog.h ui_save.h ui_basicset.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: copy3.pro  /usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/qws/linux-arm-fsl-gnueabi-g++/qmake.conf /usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/common/unix.conf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/common/linux.conf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/common/gcc-base.conf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/common/gcc-base-unix.conf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/common/g++-base.conf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/common/g++-unix.conf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/common/qws.conf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/qconfig.pri \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/modules/qt_webkit_version.pri \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/qt_functions.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/qt_config.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/exclusive_builds.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/default_pre.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/release.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/default_post.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/shared.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/warn_on.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/qt.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/unix/thread.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/moc.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/resources.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/uic.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/yacc.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/lex.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/include_source_dir.prf \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/lib/libQtSql.prl \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/lib/libQtCore.prl \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/lib/libQtXml.prl \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/lib/libQtGui.prl \
		/usr/local/Trolltech/QtEmbedded-4.8.5-arm/lib/libQtNetwork.prl
	$(QMAKE) -o Makefile copy3.pro
/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/common/unix.conf:
/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/common/linux.conf:
/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/common/gcc-base.conf:
/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/common/gcc-base-unix.conf:
/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/common/g++-base.conf:
/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/common/g++-unix.conf:
/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/common/qws.conf:
/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/qconfig.pri:
/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/modules/qt_webkit_version.pri:
/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/qt_functions.prf:
/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/qt_config.prf:
/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/exclusive_builds.prf:
/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/default_pre.prf:
/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/release.prf:
/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/default_post.prf:
/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/shared.prf:
/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/warn_on.prf:
/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/qt.prf:
/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/unix/thread.prf:
/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/moc.prf:
/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/resources.prf:
/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/uic.prf:
/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/yacc.prf:
/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/lex.prf:
/usr/local/Trolltech/QtEmbedded-4.8.5-arm/mkspecs/features/include_source_dir.prf:
/usr/local/Trolltech/QtEmbedded-4.8.5-arm/lib/libQtSql.prl:
/usr/local/Trolltech/QtEmbedded-4.8.5-arm/lib/libQtCore.prl:
/usr/local/Trolltech/QtEmbedded-4.8.5-arm/lib/libQtXml.prl:
/usr/local/Trolltech/QtEmbedded-4.8.5-arm/lib/libQtGui.prl:
/usr/local/Trolltech/QtEmbedded-4.8.5-arm/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile copy3.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/copy31.0.0 || $(MKDIR) .tmp/copy31.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/copy31.0.0/ && $(COPY_FILE) --parents GlobalVarible.h mainwindow.h newconfiginfo.h changeof351andrfid.h TestInput_Cursor/formhanzitable.h TestInput_Cursor/keyboard.h TestInput_Cursor/dialogtooltip.h TestInput_Cursor/ChineseTranslator.h TestInput_Cursor/formhanziselector.h TestInput_Cursor/formnumpad.h TestInput_Cursor/HanziManager.h TestInput_Cursor/formsymbolpad.h TestInput_Cursor/inputmethod.h TestInput_Cursor/padbase.h optiondialog.h save.h basicset.h fisupdate.h communication.h tightenthread.h xmlcreate.h inputevents.h wificonnect.h reinsertserverdb.h taotong.h sqlthread.h split.h serialcom.h .tmp/copy31.0.0/ && $(COPY_FILE) --parents file.qrc TestInput_Cursor/keypad.qrc .tmp/copy31.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp newconfiginfo.cpp changeof351andrfid.cpp TestInput_Cursor/formhanzitable.cpp TestInput_Cursor/formsymbolpad.cpp TestInput_Cursor/HanziManager.cpp TestInput_Cursor/formhanziselector.cpp TestInput_Cursor/formnumpad.cpp TestInput_Cursor/padbase.cpp TestInput_Cursor/keyboard.cpp TestInput_Cursor/dialogtooltip.cpp TestInput_Cursor/inputmethod.cpp optiondialog.cpp save.cpp basicset.cpp fisupdate.cpp communication.cpp tightenthread.cpp xmlcreate.cpp inputevents.cpp wificonnect.cpp reinsertserverdb.cpp taotong.cpp sqlthread.cpp split.cpp serialcom.cpp .tmp/copy31.0.0/ && $(COPY_FILE) --parents mainwindow.ui newconfiginfo.ui TestInput_Cursor/formsymbolpad.ui TestInput_Cursor/formnumpad.ui TestInput_Cursor/formhanziselector.ui TestInput_Cursor/keyboard.ui TestInput_Cursor/dialogtooltip.ui TestInput_Cursor/formhanzitable.ui optiondialog.ui save.ui basicset.ui .tmp/copy31.0.0/ && (cd `dirname .tmp/copy31.0.0` && $(TAR) copy31.0.0.tar copy31.0.0 && $(COMPRESS) copy31.0.0.tar) && $(MOVE) `dirname .tmp/copy31.0.0`/copy31.0.0.tar.gz . && $(DEL_FILE) -r .tmp/copy31.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_newconfiginfo.cpp moc_changeof351andrfid.cpp moc_formhanzitable.cpp moc_keyboard.cpp moc_dialogtooltip.cpp moc_formhanziselector.cpp moc_formnumpad.cpp moc_formsymbolpad.cpp moc_inputmethod.cpp moc_padbase.cpp moc_optiondialog.cpp moc_save.cpp moc_basicset.cpp moc_fisupdate.cpp moc_communication.cpp moc_tightenthread.cpp moc_xmlcreate.cpp moc_inputevents.cpp moc_wificonnect.cpp moc_reinsertserverdb.cpp moc_taotong.cpp moc_sqlthread.cpp moc_split.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_newconfiginfo.cpp moc_changeof351andrfid.cpp moc_formhanzitable.cpp moc_keyboard.cpp moc_dialogtooltip.cpp moc_formhanziselector.cpp moc_formnumpad.cpp moc_formsymbolpad.cpp moc_inputmethod.cpp moc_padbase.cpp moc_optiondialog.cpp moc_save.cpp moc_basicset.cpp moc_fisupdate.cpp moc_communication.cpp moc_tightenthread.cpp moc_xmlcreate.cpp moc_inputevents.cpp moc_wificonnect.cpp moc_reinsertserverdb.cpp moc_taotong.cpp moc_sqlthread.cpp moc_split.cpp
moc_mainwindow.cpp: GlobalVarible.h \
		newconfiginfo.h \
		optiondialog.h \
		save.h \
		basicset.h \
		mainwindow.h
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_newconfiginfo.cpp: optiondialog.h \
		save.h \
		basicset.h \
		newconfiginfo.h
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/moc $(DEFINES) $(INCPATH) newconfiginfo.h -o moc_newconfiginfo.cpp

moc_changeof351andrfid.cpp: serialcom.h \
		changeof351andrfid.h
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/moc $(DEFINES) $(INCPATH) changeof351andrfid.h -o moc_changeof351andrfid.cpp

moc_formhanzitable.cpp: TestInput_Cursor/formhanzitable.h
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/moc $(DEFINES) $(INCPATH) TestInput_Cursor/formhanzitable.h -o moc_formhanzitable.cpp

moc_keyboard.cpp: ui_keyboard.h \
		TestInput_Cursor/padbase.h \
		TestInput_Cursor/dialogtooltip.h \
		TestInput_Cursor/keyboard.h
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/moc $(DEFINES) $(INCPATH) TestInput_Cursor/keyboard.h -o moc_keyboard.cpp

moc_dialogtooltip.cpp: TestInput_Cursor/dialogtooltip.h
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/moc $(DEFINES) $(INCPATH) TestInput_Cursor/dialogtooltip.h -o moc_dialogtooltip.cpp

moc_formhanziselector.cpp: TestInput_Cursor/padbase.h \
		TestInput_Cursor/HanziManager.h \
		TestInput_Cursor/formhanziselector.h
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/moc $(DEFINES) $(INCPATH) TestInput_Cursor/formhanziselector.h -o moc_formhanziselector.cpp

moc_formnumpad.cpp: TestInput_Cursor/padbase.h \
		TestInput_Cursor/formnumpad.h
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/moc $(DEFINES) $(INCPATH) TestInput_Cursor/formnumpad.h -o moc_formnumpad.cpp

moc_formsymbolpad.cpp: TestInput_Cursor/padbase.h \
		TestInput_Cursor/formsymbolpad.h
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/moc $(DEFINES) $(INCPATH) TestInput_Cursor/formsymbolpad.h -o moc_formsymbolpad.cpp

moc_inputmethod.cpp: TestInput_Cursor/keyboard.h \
		ui_keyboard.h \
		TestInput_Cursor/padbase.h \
		TestInput_Cursor/dialogtooltip.h \
		TestInput_Cursor/inputmethod.h
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/moc $(DEFINES) $(INCPATH) TestInput_Cursor/inputmethod.h -o moc_inputmethod.cpp

moc_padbase.cpp: TestInput_Cursor/padbase.h
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/moc $(DEFINES) $(INCPATH) TestInput_Cursor/padbase.h -o moc_padbase.cpp

moc_optiondialog.cpp: optiondialog.h
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/moc $(DEFINES) $(INCPATH) optiondialog.h -o moc_optiondialog.cpp

moc_save.cpp: save.h
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/moc $(DEFINES) $(INCPATH) save.h -o moc_save.cpp

moc_basicset.cpp: basicset.h
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/moc $(DEFINES) $(INCPATH) basicset.h -o moc_basicset.cpp

moc_fisupdate.cpp: fisupdate.h
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/moc $(DEFINES) $(INCPATH) fisupdate.h -o moc_fisupdate.cpp

moc_communication.cpp: communication.h
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/moc $(DEFINES) $(INCPATH) communication.h -o moc_communication.cpp

moc_tightenthread.cpp: GlobalVarible.h \
		serialcom.h \
		tightenthread.h
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/moc $(DEFINES) $(INCPATH) tightenthread.h -o moc_tightenthread.cpp

moc_xmlcreate.cpp: xmlcreate.h
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/moc $(DEFINES) $(INCPATH) xmlcreate.h -o moc_xmlcreate.cpp

moc_inputevents.cpp: inputevents.h
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/moc $(DEFINES) $(INCPATH) inputevents.h -o moc_inputevents.cpp

moc_wificonnect.cpp: wificonnect.h
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/moc $(DEFINES) $(INCPATH) wificonnect.h -o moc_wificonnect.cpp

moc_reinsertserverdb.cpp: reinsertserverdb.h
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/moc $(DEFINES) $(INCPATH) reinsertserverdb.h -o moc_reinsertserverdb.cpp

moc_taotong.cpp: GlobalVarible.h \
		taotong.h
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/moc $(DEFINES) $(INCPATH) taotong.h -o moc_taotong.cpp

moc_sqlthread.cpp: GlobalVarible.h \
		sqlthread.h
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/moc $(DEFINES) $(INCPATH) sqlthread.h -o moc_sqlthread.cpp

moc_split.cpp: split.h
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/moc $(DEFINES) $(INCPATH) split.h -o moc_split.cpp

compiler_rcc_make_all: qrc_file.cpp qrc_keypad.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_file.cpp qrc_keypad.cpp
qrc_file.cpp: file.qrc \
		TemplateXmlString.xml \
		AliveXmlString.xml \
		ResetXmlString.xml \
		re/98.bmp \
		re/94.bmp \
		re/113.bmp \
		re/124.bmp \
		re/53.bmp \
		re/95.bmp \
		re/99.png \
		re/125.bmp \
		re/go.png \
		re/settings.png \
		re/100.png \
		re/96.bmp \
		re/num.png \
		re/92.bmp \
		re/111.bmp \
		re/126.bmp \
		re/back2.png \
		re/97.bmp \
		re/93.bmp \
		re/112.bmp \
		re/back.png \
		re/52.bmp \
		LCD_CS351/LCD_CS351/logo/warn.png \
		LCD_CS351/LCD_CS351/logo/barcode_set.png \
		LCD_CS351/LCD_CS351/logo/server.bmp \
		LCD_CS351/LCD_CS351/logo/RFID.bmp \
		LCD_CS351/LCD_CS351/logo/RFID_small.bmp \
		LCD_CS351/LCD_CS351/logo/redcha.png \
		LCD_CS351/LCD_CS351/logo/arrow.png \
		LCD_CS351/LCD_CS351/logo/check.png \
		LCD_CS351/LCD_CS351/logo/Radio_check.png \
		LCD_CS351/LCD_CS351/logo/wifi.png \
		LCD_CS351/LCD_CS351/logo/barcode.bmp \
		LCD_CS351/LCD_CS351/logo/351.bmp \
		LCD_CS351/LCD_CS351/logo/back2.png \
		LCD_CS351/LCD_CS351/logo/triangle.png \
		LCD_CS351/LCD_CS351/logo/xuan.bmp \
		LCD_CS351/LCD_CS351/logo/go.png \
		LCD_CS351/LCD_CS351/logo/line.bmp \
		LCD_CS351/LCD_CS351/logo/left_history.bmp \
		LCD_CS351/LCD_CS351/logo/on_0ff.png \
		LCD_CS351/LCD_CS351/logo/cancel.bmp \
		LCD_CS351/LCD_CS351/logo/cs351set.png \
		LCD_CS351/LCD_CS351/logo/battery.png \
		LCD_CS351/LCD_CS351/logo/battery_2.png \
		LCD_CS351/LCD_CS351/logo/saves.bmp \
		LCD_CS351/LCD_CS351/logo/Radio.png \
		LCD_CS351/LCD_CS351/logo/right_history.bmp \
		LCD_CS351/LCD_CS351/logo/go2.png \
		LCD_CS351/LCD_CS351/logo/battery_red.png \
		LCD_CS351/LCD_CS351/logo/right.jpg \
		LCD_CS351/LCD_CS351/logo/code.bmp \
		LCD_CS351/LCD_CS351/logo/battery_red_2.png \
		LCD_CS351/LCD_CS351/logo/left.jpg \
		LCD_CS351/LCD_CS351/logo/off.png \
		LCD_CS351/LCD_CS351/logo/xuanpei.bmp \
		LCD_CS351/LCD_CS351/logo/luosi.png \
		LCD_CS351/LCD_CS351/logo/back.png \
		LCD_CS351/LCD_CS351/DWIN_SET/home.bmp \
		LCD_CS351/LCD_CS351/35_all/21.bmp \
		LCD_CS351/LCD_CS351/35_all/67.bmp \
		LCD_CS351/LCD_CS351/35_all/19.bmp \
		LCD_CS351/LCD_CS351/35_all/15.bmp \
		LCD_CS351/LCD_CS351/35_all/up.bmp \
		LCD_CS351/LCD_CS351/35_all/11.bmp \
		LCD_CS351/LCD_CS351/35_all/logo.png \
		LCD_CS351/LCD_CS351/35_all/53.bmp \
		LCD_CS351/LCD_CS351/35_all/22.bmp \
		LCD_CS351/LCD_CS351/35_all/68.bmp \
		LCD_CS351/LCD_CS351/35_all/110.bmp \
		LCD_CS351/LCD_CS351/35_all/y01.png \
		LCD_CS351/LCD_CS351/35_all/16.bmp \
		LCD_CS351/LCD_CS351/35_all/12.bmp \
		LCD_CS351/LCD_CS351/35_all/9.bmp \
		LCD_CS351/LCD_CS351/35_all/001.bmp \
		LCD_CS351/LCD_CS351/35_all/5.bmp \
		LCD_CS351/LCD_CS351/35_all/cha.bmp \
		LCD_CS351/LCD_CS351/35_all/r01.png \
		LCD_CS351/LCD_CS351/35_all/50.bmp \
		LCD_CS351/LCD_CS351/35_all/69.bmp \
		LCD_CS351/LCD_CS351/35_all/17.bmp \
		LCD_CS351/LCD_CS351/35_all/13.bmp \
		LCD_CS351/LCD_CS351/35_all/6.bmp \
		LCD_CS351/LCD_CS351/35_all/down.bmp \
		LCD_CS351/LCD_CS351/35_all/20.bmp \
		LCD_CS351/LCD_CS351/35_all/w01.png \
		LCD_CS351/LCD_CS351/35_all/18.bmp \
		LCD_CS351/LCD_CS351/35_all/14.bmp \
		LCD_CS351/LCD_CS351/35_all/10.bmp \
		LCD_CS351/LCD_CS351/35_all/g01.png \
		LCD_CS351/LCD_CS351/35_all/52.bmp
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/rcc -name file file.qrc -o qrc_file.cpp

qrc_keypad.cpp: TestInput_Cursor/keypad.qrc \
		TestInput_Cursor/picture/keypad/arrow-big-03.png \
		TestInput_Cursor/picture/keypad/keyboard.jpg \
		TestInput_Cursor/picture/keypad/br_right.png \
		TestInput_Cursor/picture/keypad/down.png \
		TestInput_Cursor/picture/keypad/backspace.png \
		TestInput_Cursor/picture/keypad/left.png \
		TestInput_Cursor/picture/keypad/arrow-big-02.png \
		TestInput_Cursor/picture/keypad/br_up.png \
		TestInput_Cursor/picture/keypad/arrow-small-09.png \
		TestInput_Cursor/picture/keypad/br_down.png \
		TestInput_Cursor/picture/keypad/f0e2.png \
		TestInput_Cursor/picture/keypad/arrow-big-01.png \
		TestInput_Cursor/picture/keypad/triangle-down.png \
		TestInput_Cursor/picture/keypad/top.png \
		TestInput_Cursor/picture/keypad/triangle-left.png \
		TestInput_Cursor/picture/keypad/right.png \
		TestInput_Cursor/picture/keypad/triangle-up.png \
		TestInput_Cursor/picture/keypad/power-shutdown.png \
		TestInput_Cursor/picture/keypad/arrow-big-04.png \
		TestInput_Cursor/picture/keypad/br_left.png \
		TestInput_Cursor/picture/keypad/triangle-right.png
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/rcc -name keypad TestInput_Cursor/keypad.qrc -o qrc_keypad.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_newconfiginfo.h ui_formsymbolpad.h ui_formnumpad.h ui_formhanziselector.h ui_keyboard.h ui_dialogtooltip.h ui_formhanzitable.h ui_optiondialog.h ui_save.h ui_basicset.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_newconfiginfo.h ui_formsymbolpad.h ui_formnumpad.h ui_formhanziselector.h ui_keyboard.h ui_dialogtooltip.h ui_formhanzitable.h ui_optiondialog.h ui_save.h ui_basicset.h
ui_mainwindow.h: mainwindow.ui
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_newconfiginfo.h: newconfiginfo.ui
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/uic newconfiginfo.ui -o ui_newconfiginfo.h

ui_formsymbolpad.h: TestInput_Cursor/formsymbolpad.ui
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/uic TestInput_Cursor/formsymbolpad.ui -o ui_formsymbolpad.h

ui_formnumpad.h: TestInput_Cursor/formnumpad.ui
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/uic TestInput_Cursor/formnumpad.ui -o ui_formnumpad.h

ui_formhanziselector.h: TestInput_Cursor/formhanziselector.ui
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/uic TestInput_Cursor/formhanziselector.ui -o ui_formhanziselector.h

ui_keyboard.h: TestInput_Cursor/keyboard.ui
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/uic TestInput_Cursor/keyboard.ui -o ui_keyboard.h

ui_dialogtooltip.h: TestInput_Cursor/dialogtooltip.ui
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/uic TestInput_Cursor/dialogtooltip.ui -o ui_dialogtooltip.h

ui_formhanzitable.h: TestInput_Cursor/formhanzitable.ui
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/uic TestInput_Cursor/formhanzitable.ui -o ui_formhanzitable.h

ui_optiondialog.h: optiondialog.ui
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/uic optiondialog.ui -o ui_optiondialog.h

ui_save.h: save.ui
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/uic save.ui -o ui_save.h

ui_basicset.h: basicset.ui
	/usr/local/Trolltech/QtEmbedded-4.8.5-arm/bin/uic basicset.ui -o ui_basicset.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp GlobalVarible.h \
		changeof351andrfid.h \
		serialcom.h \
		TestInput_Cursor/inputmethod.h \
		TestInput_Cursor/keyboard.h \
		ui_keyboard.h \
		TestInput_Cursor/padbase.h \
		TestInput_Cursor/dialogtooltip.h \
		fisupdate.h \
		communication.h \
		tightenthread.h \
		xmlcreate.h \
		inputevents.h \
		wificonnect.h \
		reinsertserverdb.h \
		taotong.h \
		sqlthread.h \
		split.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

newconfiginfo.o: newconfiginfo.cpp ui_newconfiginfo.h \
		GlobalVarible.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o newconfiginfo.o newconfiginfo.cpp

changeof351andrfid.o: changeof351andrfid.cpp changeof351andrfid.h \
		serialcom.h \
		GlobalVarible.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o changeof351andrfid.o changeof351andrfid.cpp

formhanzitable.o: TestInput_Cursor/formhanzitable.cpp TestInput_Cursor/formhanzitable.h \
		ui_formhanzitable.h \
		TestInput_Cursor/formhanziselector.h \
		TestInput_Cursor/padbase.h \
		TestInput_Cursor/HanziManager.h \
		TestInput_Cursor/ChineseTranslator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o formhanzitable.o TestInput_Cursor/formhanzitable.cpp

formsymbolpad.o: TestInput_Cursor/formsymbolpad.cpp TestInput_Cursor/formsymbolpad.h \
		TestInput_Cursor/padbase.h \
		ui_formsymbolpad.h \
		TestInput_Cursor/ChineseTranslator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o formsymbolpad.o TestInput_Cursor/formsymbolpad.cpp

HanziManager.o: TestInput_Cursor/HanziManager.cpp TestInput_Cursor/HanziManager.h \
		TestInput_Cursor/ChineseTranslator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HanziManager.o TestInput_Cursor/HanziManager.cpp

formhanziselector.o: TestInput_Cursor/formhanziselector.cpp TestInput_Cursor/keyboard.h \
		ui_keyboard.h \
		TestInput_Cursor/padbase.h \
		TestInput_Cursor/dialogtooltip.h \
		TestInput_Cursor/formhanziselector.h \
		TestInput_Cursor/HanziManager.h \
		ui_formhanziselector.h \
		TestInput_Cursor/formhanzitable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o formhanziselector.o TestInput_Cursor/formhanziselector.cpp

formnumpad.o: TestInput_Cursor/formnumpad.cpp TestInput_Cursor/formnumpad.h \
		TestInput_Cursor/padbase.h \
		ui_formnumpad.h \
		TestInput_Cursor/keyboard.h \
		ui_keyboard.h \
		TestInput_Cursor/dialogtooltip.h \
		TestInput_Cursor/formsymbolpad.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o formnumpad.o TestInput_Cursor/formnumpad.cpp

padbase.o: TestInput_Cursor/padbase.cpp TestInput_Cursor/padbase.h \
		TestInput_Cursor/keyboard.h \
		ui_keyboard.h \
		TestInput_Cursor/dialogtooltip.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o padbase.o TestInput_Cursor/padbase.cpp

keyboard.o: TestInput_Cursor/keyboard.cpp TestInput_Cursor/keyboard.h \
		ui_keyboard.h \
		TestInput_Cursor/padbase.h \
		TestInput_Cursor/dialogtooltip.h \
		TestInput_Cursor/formhanziselector.h \
		TestInput_Cursor/HanziManager.h \
		TestInput_Cursor/formnumpad.h \
		TestInput_Cursor/formsymbolpad.h \
		TestInput_Cursor/ChineseTranslator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o keyboard.o TestInput_Cursor/keyboard.cpp

dialogtooltip.o: TestInput_Cursor/dialogtooltip.cpp TestInput_Cursor/dialogtooltip.h \
		ui_dialogtooltip.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialogtooltip.o TestInput_Cursor/dialogtooltip.cpp

inputmethod.o: TestInput_Cursor/inputmethod.cpp TestInput_Cursor/inputmethod.h \
		TestInput_Cursor/keyboard.h \
		ui_keyboard.h \
		TestInput_Cursor/padbase.h \
		TestInput_Cursor/dialogtooltip.h \
		TestInput_Cursor/login.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o inputmethod.o TestInput_Cursor/inputmethod.cpp

optiondialog.o: optiondialog.cpp optiondialog.h \
		ui_optiondialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o optiondialog.o optiondialog.cpp

save.o: save.cpp save.h \
		ui_save.h \
		GlobalVarible.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o save.o save.cpp

basicset.o: basicset.cpp basicset.h \
		ui_basicset.h \
		GlobalVarible.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o basicset.o basicset.cpp

fisupdate.o: fisupdate.cpp GlobalVarible.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o fisupdate.o fisupdate.cpp

communication.o: communication.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o communication.o communication.cpp

tightenthread.o: tightenthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tightenthread.o tightenthread.cpp

xmlcreate.o: xmlcreate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o xmlcreate.o xmlcreate.cpp

inputevents.o: inputevents.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o inputevents.o inputevents.cpp

wificonnect.o: wificonnect.cpp wificonnect.h \
		GlobalVarible.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wificonnect.o wificonnect.cpp

reinsertserverdb.o: reinsertserverdb.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o reinsertserverdb.o reinsertserverdb.cpp

taotong.o: taotong.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o taotong.o taotong.cpp

sqlthread.o: sqlthread.cpp sqlthread.h \
		GlobalVarible.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sqlthread.o sqlthread.cpp

split.o: split.cpp split.h \
		GlobalVarible.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o split.o split.cpp

serialcom.o: serialcom.cpp serialcom.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o serialcom.o serialcom.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_newconfiginfo.o: moc_newconfiginfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_newconfiginfo.o moc_newconfiginfo.cpp

moc_changeof351andrfid.o: moc_changeof351andrfid.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_changeof351andrfid.o moc_changeof351andrfid.cpp

moc_formhanzitable.o: moc_formhanzitable.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_formhanzitable.o moc_formhanzitable.cpp

moc_keyboard.o: moc_keyboard.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_keyboard.o moc_keyboard.cpp

moc_dialogtooltip.o: moc_dialogtooltip.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialogtooltip.o moc_dialogtooltip.cpp

moc_formhanziselector.o: moc_formhanziselector.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_formhanziselector.o moc_formhanziselector.cpp

moc_formnumpad.o: moc_formnumpad.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_formnumpad.o moc_formnumpad.cpp

moc_formsymbolpad.o: moc_formsymbolpad.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_formsymbolpad.o moc_formsymbolpad.cpp

moc_inputmethod.o: moc_inputmethod.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_inputmethod.o moc_inputmethod.cpp

moc_padbase.o: moc_padbase.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_padbase.o moc_padbase.cpp

moc_optiondialog.o: moc_optiondialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_optiondialog.o moc_optiondialog.cpp

moc_save.o: moc_save.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_save.o moc_save.cpp

moc_basicset.o: moc_basicset.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_basicset.o moc_basicset.cpp

moc_fisupdate.o: moc_fisupdate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_fisupdate.o moc_fisupdate.cpp

moc_communication.o: moc_communication.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_communication.o moc_communication.cpp

moc_tightenthread.o: moc_tightenthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tightenthread.o moc_tightenthread.cpp

moc_xmlcreate.o: moc_xmlcreate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_xmlcreate.o moc_xmlcreate.cpp

moc_inputevents.o: moc_inputevents.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_inputevents.o moc_inputevents.cpp

moc_wificonnect.o: moc_wificonnect.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wificonnect.o moc_wificonnect.cpp

moc_reinsertserverdb.o: moc_reinsertserverdb.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_reinsertserverdb.o moc_reinsertserverdb.cpp

moc_taotong.o: moc_taotong.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_taotong.o moc_taotong.cpp

moc_sqlthread.o: moc_sqlthread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sqlthread.o moc_sqlthread.cpp

moc_split.o: moc_split.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_split.o moc_split.cpp

qrc_file.o: qrc_file.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_file.o qrc_file.cpp

qrc_keypad.o: qrc_keypad.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_keypad.o qrc_keypad.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

